//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Contracts.WebUI.SalaryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoContract", Namespace="http://schemas.datacontract.org/2004/07/HR.Contracts.Services.Dto")]
    [System.SerializableAttribute()]
    public partial class DtoContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExperienceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HR.Contracts.Shared.Enums.ContractType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Experience {
            get {
                return this.ExperienceField;
            }
            set {
                if ((this.ExperienceField.Equals(value) != true)) {
                    this.ExperienceField = value;
                    this.RaisePropertyChanged("Experience");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((this.SalaryField.Equals(value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HR.Contracts.Shared.Enums.ContractType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoContractsPage", Namespace="http://schemas.datacontract.org/2004/07/HR.Contracts.Services.Dto")]
    [System.SerializableAttribute()]
    public partial class DtoContractsPage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HR.Contracts.WebUI.SalaryService.DtoContract[] ContractsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HR.Contracts.WebUI.SalaryService.DtoContract[] Contracts {
            get {
                return this.ContractsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContractsField, value) != true)) {
                    this.ContractsField = value;
                    this.RaisePropertyChanged("Contracts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((this.TotalRecordsField.Equals(value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalaryService.IContractService")]
    public interface IContractService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractService/CreateContract", ReplyAction="http://tempuri.org/IContractService/CreateContractResponse")]
        bool CreateContract(HR.Contracts.WebUI.SalaryService.DtoContract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractService/CreateContract", ReplyAction="http://tempuri.org/IContractService/CreateContractResponse")]
        System.Threading.Tasks.Task<bool> CreateContractAsync(HR.Contracts.WebUI.SalaryService.DtoContract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractService/GetAllContracts", ReplyAction="http://tempuri.org/IContractService/GetAllContractsResponse")]
        HR.Contracts.WebUI.SalaryService.DtoContractsPage GetAllContracts(HR.Contracts.Shared.Models.ColumnFilterInfo[] filterCriteria, int page, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContractService/GetAllContracts", ReplyAction="http://tempuri.org/IContractService/GetAllContractsResponse")]
        System.Threading.Tasks.Task<HR.Contracts.WebUI.SalaryService.DtoContractsPage> GetAllContractsAsync(HR.Contracts.Shared.Models.ColumnFilterInfo[] filterCriteria, int page, int pageSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContractServiceChannel : HR.Contracts.WebUI.SalaryService.IContractService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContractServiceClient : System.ServiceModel.ClientBase<HR.Contracts.WebUI.SalaryService.IContractService>, HR.Contracts.WebUI.SalaryService.IContractService {
        
        public ContractServiceClient() {
        }
        
        public ContractServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContractServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateContract(HR.Contracts.WebUI.SalaryService.DtoContract contract) {
            return base.Channel.CreateContract(contract);
        }
        
        public System.Threading.Tasks.Task<bool> CreateContractAsync(HR.Contracts.WebUI.SalaryService.DtoContract contract) {
            return base.Channel.CreateContractAsync(contract);
        }
        
        public HR.Contracts.WebUI.SalaryService.DtoContractsPage GetAllContracts(HR.Contracts.Shared.Models.ColumnFilterInfo[] filterCriteria, int page, int pageSize) {
            return base.Channel.GetAllContracts(filterCriteria, page, pageSize);
        }
        
        public System.Threading.Tasks.Task<HR.Contracts.WebUI.SalaryService.DtoContractsPage> GetAllContractsAsync(HR.Contracts.Shared.Models.ColumnFilterInfo[] filterCriteria, int page, int pageSize) {
            return base.Channel.GetAllContractsAsync(filterCriteria, page, pageSize);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SalaryService.ISalaryService")]
    public interface ISalaryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryService/CalculateSalary", ReplyAction="http://tempuri.org/ISalaryService/CalculateSalaryResponse")]
        decimal CalculateSalary(HR.Contracts.Shared.Enums.ContractType contractType, int experience);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISalaryService/CalculateSalary", ReplyAction="http://tempuri.org/ISalaryService/CalculateSalaryResponse")]
        System.Threading.Tasks.Task<decimal> CalculateSalaryAsync(HR.Contracts.Shared.Enums.ContractType contractType, int experience);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISalaryServiceChannel : HR.Contracts.WebUI.SalaryService.ISalaryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalaryServiceClient : System.ServiceModel.ClientBase<HR.Contracts.WebUI.SalaryService.ISalaryService>, HR.Contracts.WebUI.SalaryService.ISalaryService {
        
        public SalaryServiceClient() {
        }
        
        public SalaryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalaryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal CalculateSalary(HR.Contracts.Shared.Enums.ContractType contractType, int experience) {
            return base.Channel.CalculateSalary(contractType, experience);
        }
        
        public System.Threading.Tasks.Task<decimal> CalculateSalaryAsync(HR.Contracts.Shared.Enums.ContractType contractType, int experience) {
            return base.Channel.CalculateSalaryAsync(contractType, experience);
        }
    }
}
